//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResponseMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResponseMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TelegramBot.Resources.ResponseMessages", typeof(ResponseMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot recognize entered date, please enter date in mm/dd/yyyy format.
        /// </summary>
        public static string CANNOT_PARSE_DATE_MESSAGE {
            get {
                return ResourceManager.GetString("CANNOT_PARSE_DATE_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the time when it should be.
        /// </summary>
        public static string DATE_RESPONSE_MESSAGE {
            get {
                return ResourceManager.GetString("DATE_RESPONSE_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered date must be greater than or equal to today&apos;s date.
        /// </summary>
        public static string DATE_SMALLER_THAN_NOW {
            get {
                return ResourceManager.GetString("DATE_SMALLER_THAN_NOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the date when it should be.
        /// </summary>
        public static string DESCRIPTION_RESPONSE_MESSAGE {
            get {
                return ResourceManager.GetString("DESCRIPTION_RESPONSE_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot recognize entered time, please enter date in HH:mm format.
        /// </summary>
        public static string TIME_CANNOT_PARSE {
            get {
                return ResourceManager.GetString("TIME_CANNOT_PARSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event has been created successfully.
        /// </summary>
        public static string TIME_RESPONSE_MESSAGE {
            get {
                return ResourceManager.GetString("TIME_RESPONSE_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered time should be greater than now.
        /// </summary>
        public static string TIME_SMALLER_THAN_NOW {
            get {
                return ResourceManager.GetString("TIME_SMALLER_THAN_NOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi, please enter event description..
        /// </summary>
        public static string WELCOME_RESPONSE_MESSAGE {
            get {
                return ResourceManager.GetString("WELCOME_RESPONSE_MESSAGE", resourceCulture);
            }
        }
    }
}
